services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${DB_NAME:-novaiot}
      MYSQL_USER: ${DB_USER:-novaiot}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword"]
      interval: 5s
      timeout: 3s
      retries: 15

  app:
    build: .
    environment:
      PORT: 4000
      JWT_SECRET: ${JWT_SECRET:-devsecret-change-me}
      ADMIN_KEY: ${ADMIN_KEY:-NOVA-ADMIN}
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${DB_USER:-novaiot}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_NAME: ${DB_NAME:-novaiot}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@example.com}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin123}
      ADMIN_NAME: ${ADMIN_NAME:-Admin}
    expose:
      - "4000"
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "node server/seed.mjs && node server/api.mjs"

  nginx:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db_data:
